[general]
import = ["~/.config/alacritty/dark.toml"]
live_config_reload = true

[font]
size = 13
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold = { style = "ExtraBold" }
bold_italic = { style = "ExtraBold Italic" }
italic = { style = "Bold Italic" }

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { y = 8 }
opacity = 1
