[settings]
experimental = true

[tools]
deno = "latest"
go = "latest"
lua = "5.4.7"
lua-language-server = "latest"
node = "20.18.0"
postgres = "16"
python = "3.12.6"
terraform = "1.7.5"
tmux = "latest"
usage = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@prisma/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:autorandr" = "latest"
"pipx:ipython" = "latest"
"pipx:pgcli" = "latest"
"pipx:poetry" = "latest"
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:termux-language-server" = "latest"
neovim = "nightly"
"npm:eas-cli" = "latest"
