[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
env_shell_expand = false

[tools]
bun = "latest"
cargo-binstall = "latest"
deno = "latest"
fzf = "latest"
go = "latest"
lazydocker = "latest"
lua = "5.4.7"
lua-language-server = "latest"
neovim = "nightly"
node = "24.13"
postgres = "17.4"
python = "3.13.7"
terraform = "1.7.5"
tmux = "latest"
usage = "latest"

#-----------------------------------------------------------------------------#
#                                    Tools                                    #
#-----------------------------------------------------------------------------#
"cargo:bat" = "latest"
"cargo:du-dust" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:htmlq" = "latest"
"cargo:lsd" = "latest"
"cargo:lsp-ai" = "latest"
"cargo:ripgrep" = "latest"
"cargo:sd" = "latest"
"cargo:stylua" = "latest"
"cargo:tailspin" = "latest"
"cargo:taplo-cli" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:vivid" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@openai/codex" = "latest"
"npm:@prisma/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:ipython" = "latest"
"pipx:mdformat" = "latest"
"pipx:pgcli" = "latest"
"pipx:poethepoet" = "latest"
"pipx:poetry" = { version = "latest", uvx_args = "--with poetry-plugin-export" }
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:termux-language-server" = "latest"
"github:artempyanykh/marksman" = "latest"
"github:mikefarah/yq" = { version = "latest", asset_pattern = "yq_linux_amd64" }
"github:starship/starship" = "latest"
