[tools]
node = "20.17.0"
python = "3.12.6"
lua = "5.4.7"

"npm:@microsoft/compose-language-service" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:autorandr" = "latest"
"pipx:ipython" = "latest"
"pipx:pgcli" = "latest"
"pipx:poetry" = "latest"
"pipx:ruff" = "latest"
"pipx:termux-language-server" = "latest"
lua-language-server = "latest"
neovim = "nightly"
postgres = "16"
terraform = "1.7.5"
tmux = "latest"
usage = "latest"
"npm:yaml-language-server" = "latest"

[settings]
experimental = true
