[tools]
node = "20.17.0"
python = "3.12.6"
lua = "5.4.7"

neovim = "nightly"
usage = "latest"
tmux = "latest"
postgres = "16"
"npm:prettier" = "latest"
"pipx:ipython" = "latest"
"pipx:ruff" = "latest"
"pipx:poetry" = "latest"
"pipx:pgcli" = "latest"

[settings]
experimental = true
