[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
deno = "latest"
go = "latest"
lua = "5.4.7"
lua-language-server = "latest"
neovim = "nightly"
node = "22.13.1"
postgres = "16"
python = "3.13.7"
terraform = "1.7.5"
tmux = "latest"
usage = "latest"
cargo-binstall = "latest"

#-----------------------------------------------------------------------------#
#                                    Tools                                    #
#-----------------------------------------------------------------------------#
"cargo:bat" = "latest"
"cargo:du-dust" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:lsd" = "latest"
"cargo:ripgrep" = "latest"
"cargo:sd" = "latest"
"cargo:tailspin" = "latest"
"cargo:vivid" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@openai/codex" = "latest"
"npm:@prisma/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eas-cli" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:repomix" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:aider-chat" = "latest"
"pipx:autorandr" = "latest"
"pipx:basedpyright" = "latest"
"pipx:ipython" = "latest"
"pipx:pgcli" = "latest"
"pipx:poetry" = { version = "latest", uvx_args = "--with poetry-plugin-export" }
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:termux-language-server" = "latest"
"ubi:artempyanykh/marksman" = "latest"
"ubi:mikefarah/yq" = { version = "latest", matching = "yq_linux_amd64" }
"ubi:starship/starship" = "latest"
pnpm = "latest"
"npm:tree-sitter-cli" = "latest"
"cargo:stylua" = "latest"
"npm:claude-ext" = "latest"
"cargo:lsp-ai" = "latest"
"go:github.com/charmbracelet/crush" = "latest"
