local utils = require("heirline.utils")

return {
  -- bg = "#282A36",
  -- fg = "#F8F8F2",
  -- selection = "#44475A",
  -- comment = "#6272A4",
  -- red = "#FF5555",
  -- orange = "#FFB86C",
  -- yellow = "#F1FA8C",
  -- green = "#50fa7b",
  -- purple = "#BD93F9",
  -- cyan = "#8BE9FD",
  -- pink = "#FF79C6",
  -- bright_red = "#FF6E6E",
  -- bright_green = "#69FF94",
  -- bright_yellow = "#FFFFA5",
  -- bright_blue = "#D6ACFF",
  -- bright_magenta = "#FF92DF",
  -- bright_cyan = "#A4FFFF",
  -- bright_white = "#FFFFFF",
  -- menu = "#21222C",
  -- visual = "#3E4452",
  -- gutter_fg = "#4B5263",
  -- nontext = "#3B4048",
  -- white = "#ABB2BF",
  -- black = "#191A21",
    bg = utils.get_highlight("Normal").bg,
    fg = utils.get_highlight("Normal").fg,
    selection = utils.get_highlight("Visual").bg,
    comment = utils.get_highlight("Comment").fg,
    red = utils.get_highlight("Error").fg,
    orange = utils.get_highlight("Number").fg,
    yellow = utils.get_highlight("Character").fg,
    green = utils.get_highlight("Function").fg,
    purple = utils.get_highlight("Statement").fg,
    cyan = utils.get_highlight("Type").fg,
    pink = utils.get_highlight("Structure").fg,

    black = utils.get_highlight("Normal").bg,
    white = utils.get_highlight("Normal").fg,

}
